version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - cp -R ./node_modules ./packages/user-service/create-user
      - cp -R ./node_modules ./packages/user-service/send-mail
      - cd ./packages/user-service
      - ./build.sh
      - cd ../../infrastructure/applications/user-service
      - ./package.sh

artifacts:
  files:
    - ./infrastructure/applications/user-service/packaged-template.yml
  discard-paths: yes
